version: 0.2

phases:
  pre_build:
    commands:
      # login to ECR
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      # get commit hash
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      # build go app with static link
      - docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp -e CGO_ENABLED=0 -e GOOS=linux golang:alpine go build -a -installsuffix cgo -o main -v .
      # build lightweight app image which only contains the binary
      - docker build . -t $ECR_REPO:latest
      # tag image
      - docker tag $ECR_REPO:latest $ECR_REPO:$COMMIT_HASH
  post_build:
    commands:
      # push to ECR
      - docker push $ECR_REPO:latest
      - docker push $ECR_REPO:$COMMIT_HASH

