apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment-a
  labels:
    app: go-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: IMAGE_NAME:IMAGE_TAG
        ports:
        - containerPort: 8080
        affinity:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: failure-domain.beta.kubernetes.io/zone
                operator: In
                values:
                - ap-southeast-2a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment-b
  labels:
    app: go-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: IMAGE_NAME:IMAGE_TAG
        ports:
        - containerPort: 8080
        affinity:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: failure-domain.beta.kubernetes.io/zone
                operator: In
                values:
                - ap-southeast-2b